name: Format code
description: "Format code using the specified command"

inputs:
  commit-message:
    description: "Commit message for the formatting changes"
    default: "Format all files correctly"
  branch:
    description: "Branch name for the formatting changes"
    default: ${{ github.head_ref }}
  command:
    description: "Command to run for formatting"
    default: "format"
  turbo-cache:
    description: "Whether to use Turbo cache"
    default: "false"
  node-version-file:
    description: "Node.js version file to determine the version to install"
    default: ""
  NPM_TOKEN:
    description: "NPM token to authenticate to a private package registry"
    required: false

runs:
  using: "composite"

  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@5b4374b04084dc1f9032b52464284b769ac5059e # v4

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: Turbo Cache
      if: ${{ inputs.turbo-cache }}
      id: turbo-cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-

    - name: Install dependencies
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Format code
      run: pnpm run ${{ inputs.command }}
      shell: bash

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
      with:
        commit_message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
